defaultPortal: dev-practice
portals:
  - name: dev-practice
    portalId: 44685983
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLCLtsTIMRIRAA0AQAAA4C0DQAJYAgEAAMgYn7WnFSCsm-YdKO7pDDIUeRGy9wY7oL6ZKPbIEeJbntDiwG86OAAABEEAAAB4AAAAAAAAAAAAgAAAAAAABAAAwAcAjvAxPGAQBgBEAGBA_BgGABAgAwAAAAAAPAIDQhTQNHLIzAFCc4ognOPauPe4SnKDjUoDbmExUgBaAA
        expiresAt: '2023-12-20T18:47:05.413Z'
    personalAccessKey: >-
      CiQ0MTBkOTU5Yi00OWYyLTQ3N2ItOGZlNC1jOGFiYzFlMTk3MGYQn7WnFRism-YdKhkABeaRgg5yQ4Cjxn8lT519gA_DtDiXqpmMSgNuYTE
    sandboxAccountType: null
    parentAccountId: null
